-- ========================================
-- 1) TABLE CREATE (DDL)
-- ========================================

-- 사용자 계정/인증 정보
CREATE TABLE IF NOT EXISTS users (
  user_uuid CHAR(36) NOT NULL COMMENT '사용자 UUID',
  id VARCHAR(50) DEFAULT NULL COMMENT '로컬 로그인 아이디',
  email VARCHAR(255) NOT NULL COMMENT '이메일',
  password_hash VARCHAR(255) DEFAULT NULL COMMENT '비밀번호 해시',
  nickname VARCHAR(5) NOT NULL COMMENT '닉네임',
  profile_color CHAR(7) NOT NULL DEFAULT '#B7AEA6' COMMENT '프로필 색상 HEX',
  provider VARCHAR(20) NOT NULL DEFAULT 'local' COMMENT '가입 제공자(local/kakao/google/naver)',
  provider_id VARCHAR(255) DEFAULT NULL COMMENT '소셜 제공자 사용자 식별자',
  membership_plan ENUM('free', 'basic', 'pro') NOT NULL DEFAULT 'free' COMMENT '멤버십 등급',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (user_uuid),
  UNIQUE KEY uq_users_id (id),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_provider_provider_id (provider, provider_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 정보';

-- 카테고리(무드) 정보 + 고정 태그/카드 그라데이션
CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '카테고리 ID',
  mood VARCHAR(30) NOT NULL COMMENT '카테고리 키(chill/bright 등)',
  label VARCHAR(50) NOT NULL COMMENT '화면 표시 이름',
  tag1 VARCHAR(30) NOT NULL COMMENT '고정 태그 1',
  tag2 VARCHAR(30) NOT NULL COMMENT '고정 태그 2',
  tag3 VARCHAR(30) NOT NULL COMMENT '고정 태그 3',
  grad_c1 CHAR(7) NOT NULL COMMENT '그라데이션 색상 1 HEX',
  grad_c2 CHAR(7) NOT NULL COMMENT '그라데이션 색상 2 HEX',
  grad_c3 CHAR(7) NOT NULL COMMENT '그라데이션 색상 3 HEX',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (id),
  UNIQUE KEY uq_categories_mood (mood)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='카테고리 정보';

-- 곡 메타데이터 + 파일명
CREATE TABLE IF NOT EXISTS tracks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '곡 ID',
  title VARCHAR(150) NOT NULL COMMENT '곡 제목',
  artist VARCHAR(100) NOT NULL COMMENT '아티스트명',
  audio_filename VARCHAR(255) NOT NULL COMMENT '음원 파일명',
  cover_filename VARCHAR(255) NOT NULL COMMENT '커버 이미지 파일명',
  video_filename VARCHAR(255) NOT NULL DEFAULT 'movie1.mp4' COMMENT '영상 파일명',
  duration_ms INT UNSIGNED NOT NULL COMMENT '재생 길이(밀리초)',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (id),
  UNIQUE KEY uq_tracks_audio_filename (audio_filename)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='곡 기본 정보';

-- 플레이리스트 메타(색상 1개 = 플레이리스트 1개)
CREATE TABLE IF NOT EXISTS playlists (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '플레이리스트 ID',
  category_id INT UNSIGNED NOT NULL COMMENT '카테고리 ID',
  pantone_code VARCHAR(20) NOT NULL COMMENT '팬톤 코드',
  color_name VARCHAR(80) NOT NULL COMMENT '색상명',
  color_hex CHAR(7) NOT NULL COMMENT '대표 색상 HEX',

  energy_level ENUM('low', 'medium', 'high') NOT NULL COMMENT '에너지 레벨',
  emotion_temperature ENUM('cool', 'neutral', 'heated') NOT NULL COMMENT '감정 결',
  desired_mood ENUM('stability', 'focus', 'refresh', 'immersion', 'release') NOT NULL COMMENT '지금 필요한 분위기',
  day_pace ENUM('slow', 'steady', 'fast') NOT NULL COMMENT '오늘 하루의 속도감',
  record_focus ENUM('emotion', 'atmosphere', 'movement', 'recovery', 'confidence') NOT NULL COMMENT '기록에 더 남기고 싶은 축',

  like_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '좋아요 수',
  play_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '재생 수',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (id),
  UNIQUE KEY uq_playlists_pantone_code (pantone_code),
  UNIQUE KEY uq_playlists_color_hex (color_hex),
  KEY idx_playlists_category_id (category_id),
  KEY idx_playlists_recommend_tags (
    energy_level,
    emotion_temperature,
    desired_mood,
    day_pace,
    record_focus
  ),
  CONSTRAINT fk_playlists_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='색상 기반 플레이리스트';

-- 사용자별 플레이리스트 좋아요 상태
CREATE TABLE IF NOT EXISTS playlist_likes (
  user_uuid CHAR(36) NOT NULL COMMENT '사용자 UUID',
  playlist_id INT UNSIGNED NOT NULL COMMENT '플레이리스트 ID',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '좋아요 생성 시각',
  PRIMARY KEY (user_uuid, playlist_id),
  KEY idx_playlist_likes_playlist_id (playlist_id),
  CONSTRAINT fk_playlist_likes_user FOREIGN KEY (user_uuid) REFERENCES users (user_uuid) ON DELETE CASCADE,
  CONSTRAINT fk_playlist_likes_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자별 플레이리스트 좋아요 상태';

-- 사용자별 팔레트 로그 저장 목록
CREATE TABLE IF NOT EXISTS palette_logs (
  user_uuid CHAR(36) NOT NULL COMMENT '사용자 UUID',
  playlist_id INT UNSIGNED NOT NULL COMMENT '플레이리스트 ID',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '저장 시각',
  PRIMARY KEY (user_uuid, playlist_id),
  KEY idx_palette_logs_playlist_id (playlist_id),
  CONSTRAINT fk_palette_logs_user FOREIGN KEY (user_uuid) REFERENCES users (user_uuid) ON DELETE CASCADE,
  CONSTRAINT fk_palette_logs_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='유저가 저장한 팔레트 로그 목록';

-- 사용자별 날짜 기록
CREATE TABLE IF NOT EXISTS calendar_entries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '캘린더 기록 ID',
  user_uuid CHAR(36) NOT NULL COMMENT '사용자 UUID',
  entry_date DATE NOT NULL COMMENT '기록 날짜',
  playlist_id INT UNSIGNED NOT NULL COMMENT '연결된 플레이리스트 ID',
  memo TEXT DEFAULT NULL COMMENT '기록 메모',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시각',
  PRIMARY KEY (id),
  UNIQUE KEY uq_calendar_entries_user_date (user_uuid, entry_date),
  KEY idx_calendar_entries_playlist_id (playlist_id),
  CONSTRAINT fk_calendar_entries_user FOREIGN KEY (user_uuid) REFERENCES users (user_uuid) ON DELETE CASCADE,
  CONSTRAINT fk_calendar_entries_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자별 날짜 기록';

-- 플레이리스트-트랙 매핑
CREATE TABLE IF NOT EXISTS playlist_tracks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '플레이리스트 트랙 매핑 ID',
  playlist_id INT UNSIGNED NOT NULL COMMENT '플레이리스트 ID',
  track_id INT UNSIGNED NOT NULL COMMENT '트랙 ID',
  track_order SMALLINT UNSIGNED NOT NULL COMMENT '재생 순서(1부터)',
  PRIMARY KEY (id),
  UNIQUE KEY uq_playlist_tracks_playlist_track (playlist_id, track_id),
  UNIQUE KEY uq_playlist_tracks_playlist_order (playlist_id, track_order),
  KEY idx_playlist_tracks_track_id (track_id),
  CONSTRAINT fk_playlist_tracks_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE,
  CONSTRAINT fk_playlist_tracks_track FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='플레이리스트별 트랙 순서';

-- ========================================
-- 2) SEED DATA (DML)
-- ========================================

-- users 테스트 계정
INSERT INTO users (
  user_uuid,
  id,
  email,
  password_hash,
  nickname,
  profile_color,
  provider,
  provider_id,
  membership_plan
)
VALUES (
  '11111111-1111-1111-1111-111111111111',
  'testuser',
  'testuser@naver.com',
  '$2y$10$BLw.2Or1Fm9MCxgtc3NSaO4BG9bWQn/UsU6EDcK6EzopP286qSrsO',
  '테스트',
  '#B7AEA6',
  'local',
  NULL,
  'free'
)
ON DUPLICATE KEY UPDATE
  email = VALUES(email),
  password_hash = VALUES(password_hash),
  nickname = VALUES(nickname),
  profile_color = VALUES(profile_color),
  membership_plan = VALUES(membership_plan);

-- categories 기본 데이터
INSERT INTO categories (mood, label, tag1, tag2, tag3, grad_c1, grad_c2, grad_c3)
VALUES
  ('chill', 'Chill', 'Lo-fi', '재즈', '어쿠스틱', '#eaf4f4', '#f2f2ee', '#dceae8'),
  ('bright', 'Bright', '청량 K-POP', '썸', '드라이브 팝', '#cde7f0', '#a8e6cf', '#fff3b0'),
  ('energetic', 'Energetic', '댄스', 'EDM', '아이돌', '#ff5e5b', '#ff8e53', '#fdc830'),
  ('emotional', 'Emotional', '발라드', '슬픈 힙합', 'OST', '#c08497', '#8e7dbe', '#d6cadd'),
  ('groovy', 'Groovy', 'R&B', '시티팝', '네오소울', '#3ba7a0', '#1f6f78', '#274c77'),
  ('intense', 'Intense', '락', 'Drill', '다크 EDM', '#3a0ca3', '#8d314a', '#2b2d42')
ON DUPLICATE KEY UPDATE
  label = VALUES(label),
  tag1 = VALUES(tag1),
  tag2 = VALUES(tag2),
  tag3 = VALUES(tag3),
  grad_c1 = VALUES(grad_c1),
  grad_c2 = VALUES(grad_c2),
  grad_c3 = VALUES(grad_c3);

-- tracks 기본 데이터
INSERT INTO tracks (title, artist, audio_filename, cover_filename, duration_ms)
VALUES
  ('Beggin''', 'Måneskin', 'M_neskin_Beggin.mp3', 'M_neskin_Beggin.jpg', 213101),
  ('I''m a B', '화사', '화사_I_m_a_B.mp3', '화사_I_m_a_B.jpg', 168275),
  ('Unholy', 'Sam Smith', 'Sam_Smith_Unholy.mp3', 'Sam_Smith_Unholy.jpg', 157013),
  ('Paint The Town Red', 'Doja Cat', 'Doja_Cat_Paint_The_Town_Red.mp3', 'Doja_Cat_Paint_The_Town_Red.jpg', 231735),
  ('Blinding Lights', 'The Weeknd', 'The_Weeknd_Blinding_Lights.mp3', 'The_Weeknd_Blinding_Lights.jpg', 203209),
  ('bad guy', 'Billie Eilish', 'Billie_Eilish_bad_guy.mp3', 'Billie_Eilish_bad_guy.jpg', 194119),
  ('Standing Next to You', '정국', '정국_Standing_Next_to_You.mp3', '정국_Standing_Next_to_You.jpg', 206089),
  ('The Less I Know The Better', 'Tame Impala', 'Tame_Impala_The_Less_I_Know_The_Better.mp3', 'Tame_Impala_The_Less_I_Know_The_Better.jpg', 217350),
  ('매직 카펫 라이드', '자우림', '자우림_매직_카펫_라이드.mp3', '자우림_매직_카펫_라이드.jpg', 215063),
  ('good 4 u', 'Olivia Rodrigo', 'Olivia_Rodrigo_good_4_u.mp3', 'Olivia_Rodrigo_good_4_u.jpg', 178147),
  ('Levitating', 'Dua Lipa', 'Dua_Lipa_Levitating.mp3', 'Dua_Lipa_Levitating.jpg', 220843),
  ('How You Like That', '블랙핑크', '블랙핑크_How_You_Like_That.mp3', '블랙핑크_How_You_Like_That.jpg', 181371),
  ('Titanium', 'David Guetta', 'David_Guetta_Titanium.mp3', 'David_Guetta_Titanium.jpg', 245226),
  ('Levels', 'Avicii', 'Avicii_Levels.mp3', 'Avicii_Levels.jpg', 338867),
  ('Summer', 'Calvin Harris', 'Calvin_Harris_Summer.mp3', 'Calvin_Harris_Summer.jpg', 222059),
  ('이브, 프시케 그리고 푸른 수염의 아내', '르세라핌', '르세라핌_이브_프시케_그리고_푸른_수염의_아내.mp3', '르세라핌_이브_프시케_그리고_푸른_수염의_아내.jpg', 185562),
  ('Super Shy', 'NewJeans', 'NewJeans_Super_Shy.mp3', 'NewJeans_Super_Shy.jpg', 154645),
  ('Clarity', 'Zedd', 'Zedd_Clarity.mp3', 'Zedd_Clarity.jpg', 271639),
  ('Love Me A Little', '셔누X형원', '셔누X형원_Love_Me_A_Little.mp3', '셔누X형원_Love_Me_A_Little.jpg', 199645),
  ('Rather Be', 'Clean Bandit', 'Clean_Bandit_Rather_Be.mp3', 'Clean_Bandit_Rather_Be.jpg', 241023),
  ('WANNABE', 'ITZY', 'ITZY_WANNABE.mp3', 'ITZY_WANNABE.jpg', 191424),
  ('퀸카', '(여자)아이들', '여자_아이들_퀸카.mp3', '여자_아이들_퀸카.jpg', 161263),
  ('Next Level', '에스파', '에스파_Next_Level.mp3', '에스파_Next_Level.jpg', 220241),
  ('손오공', '세븐틴', '세븐틴_손오공.mp3', '세븐틴_손오공.jpg', 212764),
  ('특', 'Stray Kids', 'Stray_Kids_특.mp3', 'Stray_Kids_특.jpg', 195686),
  ('GAMBLER', '몬스타엑스', '몬스타엑스_GAMBLER.mp3', '몬스타엑스_GAMBLER.jpg', 205706),
  ('Bangarang', 'Skrillex', 'Skrillex_Bangarang.mp3', 'Skrillex_Bangarang.jpg', 216282),
  ('Lean On', 'Major Lazer', 'Major_Lazer_Lean_On.mp3', 'Major_Lazer_Lean_On.jpg', 176597),
  ('The Business', 'Tiësto', 'Ti_sto_The_Business.mp3', 'Ti_sto_The_Business.jpg', 170005),
  ('Animals', 'Martin Garrix', 'Martin_Garrix_Animals.mp3', 'Martin_Garrix_Animals.jpg', 304890),
  ('SICKO MODE', 'Travis Scott', 'Travis_Scott_SICKO_MODE.mp3', 'Travis_Scott_SICKO_MODE.jpg', 314340),
  ('Redrum', '21 Savage', '21_Savage_Redrum.mp3', '21_Savage_Redrum.jpg', 272219),
  ('HUMBLE.', 'Kendrick Lamar', 'Kendrick_Lamar_HUMBLE.mp3', 'Kendrick_Lamar_HUMBLE.jpg', 183623),
  ('Praise The Lord', 'A$AP Rocky', 'A_AP_Rocky_Praise_The_Lord.mp3', 'A_AP_Rocky_Praise_The_Lord.jpg', 206553),
  ('God''s Plan', 'Drake', 'Drake_God_s_Plan.mp3', 'Drake_God_s_Plan.jpg', 198995),
  ('METEOR', '창모', '창모_METEOR.mp3', '창모_METEOR.jpg', 196847),
  ('Artist', '지코', '지코_Artist.mp3', '지코_Artist.jpg', 202347),
  ('몸매', '박재범', '박재범_몸매.mp3', '박재범_몸매.jpg', 207215),
  ('Congratulations', 'Post Malone', 'Post_Malone_Congratulations.mp3', 'Post_Malone_Congratulations.jpg', 220293),
  ('First Class', 'Jack Harlow', 'Jack_Harlow_First_Class.mp3', 'Jack_Harlow_First_Class.jpg', 173948),
  ('ocean eyes', 'Billie Eilish', 'Billie_Eilish_ocean_eyes.mp3', 'Billie_Eilish_ocean_eyes.jpg', 202693),
  ('EVERYTHING', '검정치마', '검정치마_EVERYTHING.mp3', '검정치마_EVERYTHING.jpg', 293071),
  ('희재', '성시경', '성시경_희재.mp3', '성시경_희재.jpg', 283771),
  ('이름에게', '아이유', '아이유_이름에게.mp3', '아이유_이름에게.jpg', 289580),
  ('야생화', '박효신', '박효신_야생화.mp3', '박효신_야생화.jpg', 312092),
  ('I''m Not The Only One', 'Sam Smith', 'Sam_Smith_I_m_Not_The_Only_One.mp3', 'Sam_Smith_I_m_Not_The_Only_One.jpg', 239607),
  ('너였다면', '정승환', '정승환_너였다면.mp3', '정승환_너였다면.jpg', 272901),
  ('첫눈처럼 너에게 가겠다', '에일리', '에일리_첫눈처럼_너에게_가겠다.mp3', '에일리_첫눈처럼_너에게_가겠다.jpg', 230052),
  ('안녕', '폴킴', '폴킴_안녕.mp3', '폴킴_안녕.jpg', 231073),
  ('어땠을까', '김나영', '김나영_어땠을까.mp3', '김나영_어땠을까.jpg', 223211),
  ('비도 오고 그래서', '헤이즈', '헤이즈_비도_오고_그래서.mp3', '헤이즈_비도_오고_그래서.jpg', 205706),
  ('노력', '박원', '박원_노력.mp3', '박원_노력.jpg', 265056),
  ('홀로', '정키', '정키_홀로.mp3', '정키_홀로.jpg', 269003),
  ('밤양갱', '비비', '비비_밤양갱.mp3', '비비_밤양갱.jpg', 153241),
  ('Bye bye my blue', '백예린', '백예린_Bye_bye_my_blue.mp3', '백예린_Bye_bye_my_blue.jpg', 206298),
  ('11:11', '태연', '태연_11_11.mp3', '태연_11_11.jpg', 230446),
  ('기다리다', '윤하', '윤하_기다리다.mp3', '윤하_기다리다.jpg', 277708),
  ('안아줘', '정준일', '정준일_안아줘.mp3', '정준일_안아줘.jpg', 274882),
  ('널 사랑하지 않아', '어반자카파', '어반자카파_널_사랑하지_않아.mp3', '어반자카파_널_사랑하지_않아.jpg', 255106),
  ('그때 헤어지면 돼', '로이킴', '로이킴_그때_헤어지면_돼.mp3', '로이킴_그때_헤어지면_돼.jpg', 250056),
  ('Someone You Loved', 'Lewis Capaldi', 'Lewis_Capaldi_Someone_You_Loved.mp3', 'Lewis_Capaldi_Someone_You_Loved.jpg', 182805),
  ('Someone Like You', 'Adele', 'Adele_Someone_Like_You.mp3', 'Adele_Someone_Like_You.jpg', 290099),
  ('시차', '우원재', '우원재_시차.mp3', '우원재_시차.jpg', 196000),
  ('내 마음 들리나요', '에픽하이', '에픽하이_내_마음_들리나요.mp3', '에픽하이_내_마음_들리나요.jpg', 244854),
  ('발레리노', '리쌍', '리쌍_발레리노.mp3', '리쌍_발레리노.jpg', 267520),
  ('아퍼', '기리보이', '기리보이_아퍼.mp3', '기리보이_아퍼.jpg', 315477),
  ('미안해', '양다일', '양다일_미안해.mp3', '양다일_미안해.jpg', 230063),
  ('이별하러 가는 길', '임한별', '임한별_이별하러_가는_길.mp3', '임한별_이별하러_가는_길.jpg', 310057),
  ('Hello', '허각', '허각_Hello.mp3', '허각_Hello.jpg', 253562),
  ('인사', '멜로망스', '멜로망스_인사.mp3', '멜로망스_인사.jpg', 221031),
  ('사계', '태연', '태연_사계.mp3', '태연_사계.jpg', 189010),
  ('하얗게', '유라', '유라_하얗게.mp3', '유라_하얗게.jpg', 189568),
  ('YOU AND I', '박봄', '박봄_YOU_AND_I.mp3', '박봄_YOU_AND_I.jpg', 268725),
  ('멀어지다', '넬', '넬_멀어지다.mp3', '넬_멀어지다.jpg', 235008),
  ('한숨', '이하이', '이하이_한숨.mp3', '이하이_한숨.jpg', 278756),
  ('잘 지내자, 우리', '짙은', '짙은_잘_지내자_우리.mp3', '짙은_잘_지내자_우리.jpg', 278257),
  ('남극', '쏜애플', '쏜애플_남극.mp3', '쏜애플_남극.jpg', 238341),
  ('와리가리', '혁오', '혁오_와리가리.mp3', '혁오_와리가리.jpg', 228601),
  ('주저하는 연인들을 위해', '잔나비', '잔나비_주저하는_연인들을_위해.mp3', '잔나비_주저하는_연인들을_위해.jpg', 266008),
  ('스토커', '십센치', '십센치_스토커.mp3', '십센치_스토커.jpg', 252830),
  ('Sunday Best', 'Surfaces', 'Surfaces_Sunday_Best.mp3', 'Surfaces_Sunday_Best.jpg', 159266),
  ('Colors', '스텔라장', '스텔라장_Colors.mp3', '스텔라장_Colors.jpg', 117284),
  ('Boat', '죠지', '죠지_Boat.mp3', '죠지_Boat.jpg', 197962),
  ('가끔', 'Crush', 'Crush_가끔.mp3', 'Crush_가끔.jpg', 263655),
  ('Snooze', 'SZA', 'SZA_Snooze.mp3', 'SZA_Snooze.jpg', 203337),
  ('Best Part', 'H.E.R.', 'H_E_R_Best_Part.mp3', 'H_E_R_Best_Part.jpg', 211008),
  ('Get You', 'Daniel Caesar', 'Daniel_Caesar_Get_You.mp3', 'Daniel_Caesar_Get_You.jpg', 278180),
  ('Pink + White', 'Frank Ocean', 'Frank_Ocean_Pink_White.mp3', 'Frank_Ocean_Pink_White.jpg', 184529),
  ('그건 아마 우리의 잘못은 아닐 거야', '백예린', '백예린_그건_아마_우리의_잘못은_아닐_거야.mp3', '백예린_그건_아마_우리의_잘못은_아닐_거야.jpg', 243101),
  ('별 보러 가자', '적재', '적재_별_보러_가자.mp3', '적재_별_보러_가자.jpg', 319321),
  ('Popo', '백예린', '백예린_Popo.mp3', '백예린_Popo.jpg', 271197),
  ('이렇게 좋아해 본 적이 없어요', '치즈', '치즈_이렇게_좋아해_본_적이_없어요.mp3', '치즈_이렇게_좋아해_본_적이_없어요.jpg', 259437),
  ('끝', '권진아', '권진아_끝.mp3', '권진아_끝.jpg', 238039),
  ('Make Up', '샘김', '샘김_Make_Up.mp3', '샘김_Make_Up.jpg', 207467),
  ('자니', '프라이머리', '프라이머리_자니.mp3', '프라이머리_자니.jpg', 231840),
  ('양화대교', 'Zion.T', 'Zion_T_양화대교.mp3', 'Zion_T_양화대교.jpg', 230783),
  ('눈, 코, 입', '태양', '태양_눈_코_입.mp3', '태양_눈_코_입.jpg', 230087),
  ('좋아', '박재범', '박재범_좋아.mp3', '박재범_좋아.jpg', 245238),
  ('D (Half Moon)', '딘', '딘_D_Half_Moon.mp3', '딘_D_Half_Moon.jpg', 231178),
  ('와르르', '콜드', '콜드_와르르.mp3', '콜드_와르르.jpg', 270656),
  ('네온', '유키카', '유키카_네온.mp3', '유키카_네온.jpg', 221909),
  ('선셋', '김아름', '김아름_선셋.mp3', '김아름_선셋.jpg', 214367),
  ('사이렌', '선미', '선미_사이렌.mp3', '선미_사이렌.jpg', 200063),
  ('월급은 통장을 스칠 뿐', '스텔라장', '스텔라장_월급은_통장을_스칠_뿐.mp3', '스텔라장_월급은_통장을_스칠_뿐.jpg', 203453),
  ('춤', '도시', '도시_춤.mp3', '도시_춤.jpg', 225160),
  ('사이먼 도미닉', '사이먼 도미닉', '사이먼_도미닉_사이먼_도미닉.mp3', '사이먼_도미닉_사이먼_도미닉.jpg', 223112),
  ('Boogie On & On', '빈지노', '빈지노_Boogie_On_On.mp3', '빈지노_Boogie_On_On.jpg', 212857),
  ('고백', '다이나믹 듀오', '다이나믹_듀오_고백.mp3', '다이나믹_듀오_고백.jpg', 226403),
  ('화장 지웠어', '개코', '개코_화장_지웠어.mp3', '개코_화장_지웠어.jpg', 259379),
  ('Jasmine (prod. CODE KUNST)', 'DPR LIVE', 'DPR_LIVE_Jasmine_prod_CODE_KUNST.mp3', 'DPR_LIVE_Jasmine_prod_CODE_KUNST.jpg', 204835),
  ('Day 1 ◑', 'Honne', 'Honne_Day_1.mp3', 'Honne_Day_1.jpg', 233511),
  ('Over', 'Lucky Daye', 'Lucky_Daye_Over.mp3', 'Lucky_Daye_Over.jpg', 205276),
  ('Texas Sun', 'Khruangbin', 'Khruangbin_Texas_Sun.mp3', 'Khruangbin_Texas_Sun.jpg', 252821),
  ('Leave The Door Open', 'Anderson .Paak', 'Anderson_Paak_Leave_The_Door_Open.mp3', 'Anderson_Paak_Leave_The_Door_Open.jpg', 248291),
  ('Treasure', 'Bruno Mars', 'Bruno_Mars_Treasure.mp3', 'Bruno_Mars_Treasure.jpg', 176093),
  ('Fly As Me', 'Silk Sonic', 'Silk_Sonic_Fly_As_Me.mp3', 'Silk_Sonic_Fly_As_Me.jpg', 219661),
  ('LMLY', '잭슨', '잭슨_LMLY.mp3', '잭슨_LMLY.jpg', 210083),
  ('머리어깨무릎발', '이하이', '이하이_머리어깨무릎발.mp3', '이하이_머리어깨무릎발.jpg', 213891),
  ('적외선 카메라', '원슈타인', '원슈타인_적외선_카메라.mp3', '원슈타인_적외선_카메라.jpg', 206042),
  ('나비', '비비', '비비_나비.mp3', '비비_나비.jpg', 193028),
  ('Happy', 'Pharrell Williams', 'Pharrell_Williams_Happy.mp3', 'Pharrell_Williams_Happy.jpg', 232571),
  ('라일락', '아이유', '아이유_라일락.mp3', '아이유_라일락.jpg', 214251),
  ('Dynamite', 'BTS', 'BTS_Dynamite.mp3', 'BTS_Dynamite.jpg', 200226),
  ('Dun Dun Dance', '오마이걸', '오마이걸_Dun_Dun_Dance.mp3', '오마이걸_Dun_Dun_Dance.jpg', 217873),
  ('빨간 맛', '레드벨벳', '레드벨벳_빨간_맛.mp3', '레드벨벳_빨간_맛.jpg', 205055),
  ('Alcohol-Free', '트와이스', '트와이스_Alcohol_Free.mp3', '트와이스_Alcohol_Free.jpg', 212648),
  ('다시 만난 세계', '소녀시대', '소녀시대_다시_만난_세계.mp3', '소녀시대_다시_만난_세계.jpg', 267320),
  ('나로 말할 것 같으면', '마마무', '마마무_나로_말할_것_같으면.mp3', '마마무_나로_말할_것_같으면.jpg', 220346),
  ('파이팅 해야지', '부석순', '부석순_파이팅_해야지.mp3', '부석순_파이팅_해야지.jpg', 209003),
  ('우주를 줄게', '볼빨간사춘기', '볼빨간사춘기_우주를_줄게.mp3', '볼빨간사춘기_우주를_줄게.jpg', 216015),
  ('Hype Boy', 'NewJeans', 'NewJeans_Hype_Boy.mp3', 'NewJeans_Hype_Boy.jpg', 180001),
  ('여행', '볼빨간사춘기', '볼빨간사춘기_여행.mp3', '볼빨간사춘기_여행.jpg', 221035),
  ('Don''t Feel Like Crying', 'Sigrid', 'Sigrid_Don_t_Feel_Like_Crying.mp3', 'Sigrid_Don_t_Feel_Like_Crying.jpg', 158528),
  ('2002', 'Anne-Marie', 'Anne_Marie_2002.mp3', 'Anne_Marie_2002.jpg', 186990),
  ('California Gurls', 'Katy Perry', 'Katy_Perry_California_Gurls.mp3', 'Katy_Perry_California_Gurls.jpg', 235845),
  ('What Makes You Beautiful', '원디렉션', '원디렉션_What_Makes_You_Beautiful.mp3', '원디렉션_What_Makes_You_Beautiful.jpg', 200342),
  ('After School', '위클리', '위클리_After_School.mp3', '위클리_After_School.jpg', 205404),
  ('ASAP', '스테이씨', '스테이씨_ASAP.mp3', '스테이씨_ASAP.jpg', 191948),
  ('WE GO', '프로미스나인', '프로미스나인_WE_GO.mp3', '프로미스나인_WE_GO.jpg', 176553),
  ('Love U', '청하', '청하_Love_U.mp3', '청하_Love_U.jpg', 192052),
  ('한 페이지가 될 수 있게', 'DAY6', 'DAY6_한_페이지가_될_수_있게.mp3', 'DAY6_한_페이지가_될_수_있게.jpg', 207595),
  ('안녕', '조이', '조이_안녕.mp3', '조이_안녕.jpg', 218744),
  ('개화', '루시', '루시_개화.mp3', '루시_개화.jpg', 251368),
  ('행운을 빌어요', '페퍼톤스', '페퍼톤스_행운을_빌어요.mp3', '페퍼톤스_행운을_빌어요.jpg', 260651),
  ('들었다 놨다', '데이브레이크', '데이브레이크_들었다_놨다.mp3', '데이브레이크_들었다_놨다.jpg', 223411),
  ('비바 청춘', '딕펑스', '딕펑스_비바_청춘.mp3', '딕펑스_비바_청춘.jpg', 240071),
  ('살빼지 마요', '소란', '소란_살빼지_마요.mp3', '소란_살빼지_마요.jpg', 248210),
  ('옥탑방', '엔플라잉', '엔플라잉_옥탑방.mp3', '엔플라잉_옥탑방.jpg', 210859),
  ('선물', '멜로망스', '멜로망스_선물.mp3', '멜로망스_선물.jpg', 261085),
  ('뜨거운 여름밤은 가고 남은 건 볼품없지만', '잔나비', '잔나비_뜨거운_여름밤은_가고_남은_건_볼품없지만.mp3', '잔나비_뜨거운_여름밤은_가고_남은_건_볼품없지만.jpg', 243450),
  ('Lover', 'Taylor Swift', 'Taylor_Swift_Lover.mp3', 'Taylor_Swift_Lover.jpg', 229333),
  ('폰서트', '10CM', '10CM_폰서트.mp3', '10CM_폰서트.jpg', 197504),
  ('봄이 좋냐??', '십센치', '십센치_봄이_좋냐.mp3', '십센치_봄이_좋냐.jpg', 205775),
  ('썸', '소유X정기고', '소유X정기고_썸.mp3', '소유X정기고_썸.jpg', 211464),
  ('200%', '악뮤', '악뮤_200.mp3', '악뮤_200.jpg', 210219),
  ('Dream', '수지X백현', '수지X백현_Dream.mp3', '수지X백현_Dream.jpg', 222401),
  ('봄인가 봐', '에릭남X웬디', '에릭남X웬디_봄인가_봐.mp3', '에릭남X웬디_봄인가_봐.jpg', 198902),
  ('우연히 봄', '로꼬X유주', '로꼬X유주_우연히_봄.mp3', '로꼬X유주_우연히_봄.jpg', 201038),
  ('나의 X에게', '경서', '경서_나의_X에게.mp3', '경서_나의_X에게.jpg', 190613),
  ('너를 생각해', '주시크', '주시크_너를_생각해.mp3', '주시크_너를_생각해.jpg', 214262),
  ('Heavenly', 'Cigarettes After Sex', 'Cigarettes_After_Sex_Heavenly.mp3', 'Cigarettes_After_Sex_Heavenly.jpg', 286790),
  ('Fragile', 'Laufey', 'Laufey_Fragile.mp3', 'Laufey_Fragile.jpg', 239978),
  ('Malibu Nights', 'LANY', 'LANY_Malibu_Nights.mp3', 'LANY_Malibu_Nights.jpg', 286952),
  ('너를 사랑하진 않아 (feat. 케이시)', '자이언트 핑크', '자이언트_핑크_너를_사랑하진_않아_feat_케이시.mp3', '자이언트_핑크_너를_사랑하진_않아_feat_케이시.jpg', 190566),
  ('자랑', '곽진언', '곽진언_자랑.mp3', '곽진언_자랑.jpg', 271275),
  ('가을방학', '가을방학', '가을방학_가을방학.mp3', '가을방학_가을방학.jpg', 254200),
  ('보러 가자', '루시드폴', '루시드폴_보러_가자.mp3', '루시드폴_보러_가자.jpg', 325299),
  ('거리에서', '김광석', '김광석_거리에서.mp3', '김광석_거리에서.jpg', 293227),
  ('사랑 그 쓸쓸함에 대하여', '양희은', '양희은_사랑_그_쓸쓸함에_대하여.mp3', '양희은_사랑_그_쓸쓸함에_대하여.jpg', 276219),
  ('가리워진 길', '유재하', '유재하_가리워진_길.mp3', '유재하_가리워진_길.jpg', 211592),
  ('Show Me How', 'Men I Trust', 'Men_I_Trust_Show_Me_How.mp3', 'Men_I_Trust_Show_Me_How.jpg', 215098),
  ('기다린 만큼, 더', '검정치마', '검정치마_기다린_만큼_더.mp3', '검정치마_기다린_만큼_더.jpg', 272869),
  ('Tomboy', '혁오', '혁오_Tomboy.mp3', '혁오_Tomboy.jpg', 241963),
  ('나무', '카더가든', '카더가든_나무.mp3', '카더가든_나무.jpg', 232641),
  ('밤, 바다', '최유리', '최유리_밤_바다.mp3', '최유리_밤_바다.jpg', 254885),
  ('머리맡', '김사월', '김사월_머리맡.mp3', '김사월_머리맡.jpg', 190009),
  ('바람이 분다', '이소라', '이소라_바람이_분다.mp3', '이소라_바람이_분다.jpg', 236809),
  ('좋은 사람 (feat. 김형중)', '토이', '토이_좋은_사람_feat_김형중.mp3', '토이_좋은_사람_feat_김형중.jpg', 267656),
  ('소박했던, 행복했던', '유희열', '유희열_소박했던_행복했던.mp3', '유희열_소박했던_행복했던.jpg', 223527),
  ('환란일기', '정밀아', '정밀아_환란일기.mp3', '정밀아_환란일기.jpg', 277500),
  ('고양이 (feat.IU)', '선우정아', '선우정아_고양이_feat_IU.mp3', '선우정아_고양이_feat_IU.jpg', 192598),
  ('위로', '권진아', '권진아_위로.mp3', '권진아_위로.jpg', 197045),
  ('바래진 기억에', '박지윤', '박지윤_바래진_기억에.mp3', '박지윤_바래진_기억에.jpg', 289460),
  ('빨래', '이적', '이적_빨래.mp3', '이적_빨래.jpg', 231097),
  ('기억의 습작', '김동률', '김동률_기억의_습작.mp3', '김동률_기억의_습작.jpg', 308814),
  ('오르막길', '윤종신', '윤종신_오르막길.mp3', '윤종신_오르막길.jpg', 290006),
  ('사랑이 우릴 다시 만나게 한다면', '박새별', '박새별_사랑이_우릴_다시_만나게_한다면.mp3', '박새별_사랑이_우릴_다시_만나게_한다면.jpg', 305707),
  ('누군가를 사랑한다는 것', '루네', '루네_누군가를_사랑한다는_것.mp3', '루네_누군가를_사랑한다는_것.jpg', 283934),
  ('비밀의 화원', '이상은', '이상은_비밀의_화원.mp3', '이상은_비밀의_화원.jpg', 252016),
  ('멜로디로 가득한 고백', '한희정', '한희정_멜로디로_가득한_고백.mp3', '한희정_멜로디로_가득한_고백.jpg', 212706),
  ('Nothing', 'Bruno Major', 'Bruno_Major_Nothing.mp3', 'Bruno_Major_Nothing.jpg', 165407),
  ('2 soon', 'Keshi', 'Keshi_2_soon.mp3', 'Keshi_2_soon.jpg', 206512),
  ('Beeeee', '정세운', '정세운_Beeeee.mp3', '정세운_Beeeee.jpg', 178039),
  ('좋아해', '치즈', '치즈_좋아해.mp3', '치즈_좋아해.jpg', 219605),
  ('그 여름밤', '샘김', '샘김_그_여름밤.mp3', '샘김_그_여름밤.jpg', 249792),
  ('하늘바라기', '정은지', '정은지_하늘바라기.mp3', '정은지_하늘바라기.jpg', 220519),
  ('동화', '멜로망스', '멜로망스_동화.mp3', '멜로망스_동화.jpg', 230017),
  ('고래', '짙은', '짙은_고래.mp3', '짙은_고래.jpg', 239979),
  ('선인장', '에피톤 프로젝트', '에피톤_프로젝트_선인장.mp3', '에피톤_프로젝트_선인장.jpg', 208678),
  ('가끔 미치도록 네가 안고 싶어질 때가 있어', '가을방학', '가을방학_가끔_미치도록_네가_안고_싶어질_때가_있어.mp3', '가을방학_가끔_미치도록_네가_안고_싶어질_때가_있어.jpg', 246120),
  ('SICKO MODE', 'Travis Scott', 'Travis_Scott_SICKO_MODE_2.mp3', 'Travis_Scott_SICKO_MODE_2.jpg', 314340),
  ('Enter Sandman', 'Metallica', 'Metallica_Enter_Sandman.mp3', 'Metallica_Enter_Sandman.jpg', 331560),
  ('Uprising', 'Muse', 'Muse_Uprising.mp3', 'Muse_Uprising.jpg', 307676),
  ('Creep', 'Radiohead', 'Radiohead_Creep.mp3', 'Radiohead_Creep.jpg', 240001),
  ('교실 이데아', '서태지와 아이들', '서태지와_아이들_교실_이데아.mp3', '서태지와_아이들_교실_이데아.jpg', 257869),
  ('소용돌이', '피아', '피아_소용돌이.mp3', '피아_소용돌이.jpg', 195233),
  ('Stay', '넬', '넬_Stay.mp3', '넬_Stay.jpg', 219000),
  ('NO PAIN', '실리카겔', '실리카겔_NO_PAIN.mp3', '실리카겔_NO_PAIN.jpg', 222354),
  ('거울', '국카스텐', '국카스텐_거울.mp3', '국카스텐_거울.jpg', 279499),
  ('Can You Feel My Heart', 'Bring Me The Horizon', 'Bring_Me_The_Horizon_Can_You_Feel_My_Heart.mp3', 'Bring_Me_The_Horizon_Can_You_Feel_My_Heart.jpg', 228299),
  ('I WANNA BE YOUR SLAVE', 'Måneskin', 'M_neskin_I_WANNA_BE_YOUR_SLAVE.mp3', 'M_neskin_I_WANNA_BE_YOUR_SLAVE.jpg', 173395),
  ('Numb', 'Linkin Park', 'Linkin_Park_Numb.mp3', 'Linkin_Park_Numb.jpg', 187520),
  ('Bring Me To Life', 'Evanescence', 'Evanescence_Bring_Me_To_Life.mp3', 'Evanescence_Bring_Me_To_Life.jpg', 236400),
  ('크게 라디오를 켜고', '시나위', '시나위_크게_라디오를_켜고.mp3', '시나위_크게_라디오를_켜고.jpg', 261155),
  ('나를 슬프게 하는 사람들', '김경호', '김경호_나를_슬프게_하는_사람들.mp3', '김경호_나를_슬프게_하는_사람들.jpg', 260840),
  ('박하사탕', '윤도현밴드', '윤도현밴드_박하사탕.mp3', '윤도현밴드_박하사탕.jpg', 290333),
  ('하하하쏭', '자우림', '자우림_하하하쏭.mp3', '자우림_하하하쏭.jpg', 193840),
  ('라젠카, 세이브 어스', '국카스텐', '국카스텐_라젠카_세이브_어스.mp3', '국카스텐_라젠카_세이브_어스.jpg', 208086),
  ('Scary Monsters', 'Skrillex', 'Skrillex_Scary_Monsters.mp3', 'Skrillex_Scary_Monsters.jpg', 245098),
  ('Bonfire', 'Knife Party', 'Knife_Party_Bonfire.mp3', 'Knife_Party_Bonfire.jpg', 272208),
  ('Alone', 'Marshmello', 'Marshmello_Alone.mp3', 'Marshmello_Alone.jpg', 277246),
  ('Faded', 'Alan Walker', 'Alan_Walker_Faded.mp3', 'Alan_Walker_Faded.jpg', 212683),
  ('Tremor', 'Martin Garrix', 'Martin_Garrix_Tremor.mp3', 'Martin_Garrix_Tremor.jpg', 198400),
  ('Turn Down for What', 'DJ Snake', 'DJ_Snake_Turn_Down_for_What.mp3', 'DJ_Snake_Turn_Down_for_What.jpg', 215808),
  ('Strobe', 'Deadmau5', 'Deadmau5_Strobe.mp3', 'Deadmau5_Strobe.jpg', 214186),
  ('Harder, Better, Faster, Stronger', 'Daft Punk', 'Daft_Punk_Harder_Better_Faster_Stronger.mp3', 'Daft_Punk_Harder_Better_Faster_Stronger.jpg', 224688),
  ('D.A.N.C.E.', 'Justice', 'Justice_D_A_N_C_E.mp3', 'Justice_D_A_N_C_E.jpg', 242254),
  ('Pursuit', 'Gesaffelstein', 'Gesaffelstein_Pursuit.mp3', 'Gesaffelstein_Pursuit.jpg', 305003),
  ('HUMBLE.', 'Kendrick Lamar', 'Kendrick_Lamar_HUMBLE_2.mp3', 'Kendrick_Lamar_HUMBLE_2.jpg', 183612),
  ('Rockstar', 'Post Malone', 'Post_Malone_Rockstar.mp3', 'Post_Malone_Rockstar.jpg', 217954),
  ('a lot', '21 Savage', '21_Savage_a_lot.mp3', '21_Savage_a_lot.jpg', 288640),
  ('Doja', 'Central Cee', 'Central_Cee_Doja.mp3', 'Central_Cee_Doja.jpg', 105918),
  ('Dior', 'Pop Smoke', 'Pop_Smoke_Dior.mp3', 'Pop_Smoke_Dior.jpg', 216384),
  ('Look At Me!', 'XXXTENTACION', 'XXXTENTACION_Look_At_Me.mp3', 'XXXTENTACION_Look_At_Me.jpg', 127338),
  ('Kill Yourself (Part III)', '$uicideboy$', 'uicideboy_Kill_Yourself_Part_III.mp3', 'uicideboy_Kill_Yourself_Part_III.jpg', 145078),
  ('EARFQUAKE', 'Tyler, The Creator', 'Tyler_The_Creator_EARFQUAKE.mp3', 'Tyler_The_Creator_EARFQUAKE.jpg', 190090),
  ('Magnolia', 'Playboi Carti', 'Playboi_Carti_Magnolia.mp3', 'Playboi_Carti_Magnolia.jpg', 180500),
  ('XO Tour Llif3', 'Lil Uzi Vert', 'Lil_Uzi_Vert_XO_Tour_Llif3.mp3', 'Lil_Uzi_Vert_XO_Tour_Llif3.jpg', 180175)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  artist = VALUES(artist),
  cover_filename = VALUES(cover_filename),
  duration_ms = VALUES(duration_ms);

-- playlists 기본 데이터 + 추천 태그 포함
INSERT INTO playlists (
  category_id,
  pantone_code,
  color_name,
  color_hex,
  energy_level,
  emotion_temperature,
  desired_mood,
  day_pace,
  record_focus,
  like_count,
  play_count
)
VALUES
  ((SELECT id FROM categories WHERE mood = 'energetic'), '18-1750', 'Viva Magenta', '#BB2649', 'high', 'heated', 'release', 'fast', 'confidence', 18234, 48652),
  ((SELECT id FROM categories WHERE mood = 'energetic'), '18-4245', 'Electric Blue', '#003399', 'high', 'cool', 'focus', 'fast', 'movement', 17680, 45219),
  ((SELECT id FROM categories WHERE mood = 'energetic'), '18-1664', 'Fiery Red', '#FF0000', 'high', 'heated', 'immersion', 'fast', 'confidence', 17142, 43981),
  ((SELECT id FROM categories WHERE mood = 'energetic'), '14-0760', 'Cyber Yellow', '#FFD300', 'high', 'heated', 'refresh', 'fast', 'movement', 16537, 42108),

  ((SELECT id FROM categories WHERE mood = 'emotional'), '19-4052', 'Classic Blue', '#0F4C81', 'low', 'cool', 'stability', 'slow', 'emotion', 15984, 40567),
  ((SELECT id FROM categories WHERE mood = 'emotional'), '16-4120', 'Dusk Blue', '#779ECB', 'low', 'neutral', 'stability', 'slow', 'recovery', 15431, 39240),
  ((SELECT id FROM categories WHERE mood = 'emotional'), '19-4007', 'Anthracite', '#28282D', 'low', 'cool', 'immersion', 'slow', 'emotion', 14902, 38155),
  ((SELECT id FROM categories WHERE mood = 'emotional'), '18-3834', 'Deep Wisteria', '#615694', 'medium', 'neutral', 'immersion', 'steady', 'emotion', 14388, 36994),

  ((SELECT id FROM categories WHERE mood = 'groovy'), '16-1546', 'Living Coral', '#FF6F61', 'medium', 'heated', 'refresh', 'steady', 'movement', 13876, 35841),
  ((SELECT id FROM categories WHERE mood = 'groovy'), '16-1544', 'Peach Echo', '#F47362', 'medium', 'heated', 'refresh', 'steady', 'atmosphere', 13342, 34720),
  ((SELECT id FROM categories WHERE mood = 'groovy'), '18-3838', 'Ultra Violet', '#5F4B8B', 'medium', 'neutral', 'immersion', 'steady', 'atmosphere', 12895, 33578),
  ((SELECT id FROM categories WHERE mood = 'groovy'), '16-0952', 'Nugget Gold', '#C89720', 'medium', 'heated', 'release', 'steady', 'confidence', 12437, 32496),

  ((SELECT id FROM categories WHERE mood = 'bright'), '13-0647', 'Illuminating', '#F5DF4D', 'high', 'heated', 'refresh', 'fast', 'confidence', 11984, 31320),
  ((SELECT id FROM categories WHERE mood = 'bright'), '12-0743', 'Sunny Lime', '#E2EF44', 'high', 'heated', 'refresh', 'fast', 'recovery', 11562, 30288),
  ((SELECT id FROM categories WHERE mood = 'bright'), '14-4318', 'Sky Blue', '#87CEEB', 'medium', 'cool', 'refresh', 'steady', 'atmosphere', 11108, 29144),
  ((SELECT id FROM categories WHERE mood = 'bright'), '14-2311', 'Prism Pink', '#F0A1BF', 'medium', 'heated', 'refresh', 'steady', 'confidence', 10674, 28037),

  ((SELECT id FROM categories WHERE mood = 'chill'), '11-4201', 'Cloud Dancer', '#F0F3F4', 'low', 'cool', 'stability', 'slow', 'recovery', 10225, 26913),
  ((SELECT id FROM categories WHERE mood = 'chill'), '14-4102', 'Glacier Gray', '#C4C7C9', 'low', 'neutral', 'stability', 'slow', 'emotion', 9804, 25877),
  ((SELECT id FROM categories WHERE mood = 'chill'), '16-3801', 'Quiet Shade', '#929497', 'low', 'cool', 'focus', 'steady', 'atmosphere', 9416, 24865),
  ((SELECT id FROM categories WHERE mood = 'chill'), '15-1214', 'Warm Sand', '#C5B097', 'low', 'heated', 'stability', 'slow', 'recovery', 9032, 23840),

  ((SELECT id FROM categories WHERE mood = 'intense'), '19-4028', 'Insignia Blue', '#2E3D59', 'high', 'cool', 'focus', 'fast', 'emotion', 8674, 22818),
  ((SELECT id FROM categories WHERE mood = 'intense'), '19-1650', 'Biking Red', '#612129', 'high', 'heated', 'release', 'fast', 'movement', 8419, 21904),
  ((SELECT id FROM categories WHERE mood = 'intense'), '19-0303', 'Jet Black', '#2B2C2D', 'high', 'neutral', 'immersion', 'fast', 'movement', 8236, 21057),
  ((SELECT id FROM categories WHERE mood = 'intense'), '18-1306', 'Iron', '#735B52', 'medium', 'neutral', 'focus', 'steady', 'confidence', 8055, 20311)
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  color_name = VALUES(color_name),
  color_hex = VALUES(color_hex),
  energy_level = VALUES(energy_level),
  emotion_temperature = VALUES(emotion_temperature),
  desired_mood = VALUES(desired_mood),
  day_pace = VALUES(day_pace),
  record_focus = VALUES(record_focus),
  like_count = VALUES(like_count),
  play_count = VALUES(play_count);

-- playlist_tracks 기본 데이터
INSERT INTO playlist_tracks (playlist_id, track_id, track_order)
VALUES
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'M_neskin_Beggin.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = '화사_I_m_a_B.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'Sam_Smith_Unholy.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'Doja_Cat_Paint_The_Town_Red.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'The_Weeknd_Blinding_Lights.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'Billie_Eilish_bad_guy.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = '정국_Standing_Next_to_You.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'Tame_Impala_The_Less_I_Know_The_Better.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = '자우림_매직_카펫_라이드.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1750'), (SELECT id FROM tracks WHERE audio_filename = 'Olivia_Rodrigo_good_4_u.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'Dua_Lipa_Levitating.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = '블랙핑크_How_You_Like_That.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'David_Guetta_Titanium.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'Avicii_Levels.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'Calvin_Harris_Summer.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = '르세라핌_이브_프시케_그리고_푸른_수염의_아내.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'NewJeans_Super_Shy.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'Zedd_Clarity.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = '셔누X형원_Love_Me_A_Little.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-4245'), (SELECT id FROM tracks WHERE audio_filename = 'Clean_Bandit_Rather_Be.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'ITZY_WANNABE.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = '여자_아이들_퀸카.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = '에스파_Next_Level.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = '세븐틴_손오공.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'Stray_Kids_특.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = '몬스타엑스_GAMBLER.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'Skrillex_Bangarang.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'Major_Lazer_Lean_On.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'Ti_sto_The_Business.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1664'), (SELECT id FROM tracks WHERE audio_filename = 'Martin_Garrix_Animals.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'Travis_Scott_SICKO_MODE.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = '21_Savage_Redrum.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'Kendrick_Lamar_HUMBLE.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'A_AP_Rocky_Praise_The_Lord.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'Drake_God_s_Plan.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = '창모_METEOR.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = '지코_Artist.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = '박재범_몸매.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'Post_Malone_Congratulations.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '14-0760'), (SELECT id FROM tracks WHERE audio_filename = 'Jack_Harlow_First_Class.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = 'Billie_Eilish_ocean_eyes.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '검정치마_EVERYTHING.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '성시경_희재.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '아이유_이름에게.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '박효신_야생화.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = 'Sam_Smith_I_m_Not_The_Only_One.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '정승환_너였다면.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '에일리_첫눈처럼_너에게_가겠다.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '폴킴_안녕.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4052'), (SELECT id FROM tracks WHERE audio_filename = '김나영_어땠을까.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '헤이즈_비도_오고_그래서.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '박원_노력.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '정키_홀로.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '비비_밤양갱.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '백예린_Bye_bye_my_blue.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '태연_11_11.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '윤하_기다리다.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '정준일_안아줘.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '어반자카파_널_사랑하지_않아.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '16-4120'), (SELECT id FROM tracks WHERE audio_filename = '로이킴_그때_헤어지면_돼.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = 'Lewis_Capaldi_Someone_You_Loved.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = 'Adele_Someone_Like_You.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '우원재_시차.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '에픽하이_내_마음_들리나요.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '리쌍_발레리노.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '기리보이_아퍼.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '양다일_미안해.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '임한별_이별하러_가는_길.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '허각_Hello.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4007'), (SELECT id FROM tracks WHERE audio_filename = '멜로망스_인사.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '태연_사계.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '유라_하얗게.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '박봄_YOU_AND_I.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '넬_멀어지다.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '이하이_한숨.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '짙은_잘_지내자_우리.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '쏜애플_남극.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '혁오_와리가리.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '잔나비_주저하는_연인들을_위해.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3834'), (SELECT id FROM tracks WHERE audio_filename = '십센치_스토커.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'Surfaces_Sunday_Best.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = '스텔라장_Colors.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = '죠지_Boat.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'Crush_가끔.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'SZA_Snooze.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'H_E_R_Best_Part.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'Daniel_Caesar_Get_You.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = 'Frank_Ocean_Pink_White.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = '백예린_그건_아마_우리의_잘못은_아닐_거야.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1546'), (SELECT id FROM tracks WHERE audio_filename = '적재_별_보러_가자.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '백예린_Popo.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '치즈_이렇게_좋아해_본_적이_없어요.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '권진아_끝.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '샘김_Make_Up.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '프라이머리_자니.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = 'Zion_T_양화대교.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '태양_눈_코_입.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '박재범_좋아.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '딘_D_Half_Moon.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '16-1544'), (SELECT id FROM tracks WHERE audio_filename = '콜드_와르르.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '유키카_네온.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '김아름_선셋.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '선미_사이렌.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '스텔라장_월급은_통장을_스칠_뿐.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '도시_춤.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '사이먼_도미닉_사이먼_도미닉.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '빈지노_Boogie_On_On.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '다이나믹_듀오_고백.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = '개코_화장_지웠어.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-3838'), (SELECT id FROM tracks WHERE audio_filename = 'DPR_LIVE_Jasmine_prod_CODE_KUNST.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Honne_Day_1.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Lucky_Daye_Over.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Khruangbin_Texas_Sun.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Anderson_Paak_Leave_The_Door_Open.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Bruno_Mars_Treasure.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = 'Silk_Sonic_Fly_As_Me.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = '잭슨_LMLY.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = '이하이_머리어깨무릎발.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = '원슈타인_적외선_카메라.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '16-0952'), (SELECT id FROM tracks WHERE audio_filename = '비비_나비.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = 'Pharrell_Williams_Happy.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '아이유_라일락.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = 'BTS_Dynamite.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '오마이걸_Dun_Dun_Dance.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '레드벨벳_빨간_맛.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '트와이스_Alcohol_Free.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '소녀시대_다시_만난_세계.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '마마무_나로_말할_것_같으면.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '부석순_파이팅_해야지.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '13-0647'), (SELECT id FROM tracks WHERE audio_filename = '볼빨간사춘기_우주를_줄게.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = 'NewJeans_Hype_Boy.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '볼빨간사춘기_여행.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = 'Sigrid_Don_t_Feel_Like_Crying.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = 'Anne_Marie_2002.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = 'Katy_Perry_California_Gurls.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '원디렉션_What_Makes_You_Beautiful.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '위클리_After_School.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '스테이씨_ASAP.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '프로미스나인_WE_GO.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '12-0743'), (SELECT id FROM tracks WHERE audio_filename = '청하_Love_U.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = 'DAY6_한_페이지가_될_수_있게.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '조이_안녕.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '루시_개화.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '페퍼톤스_행운을_빌어요.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '데이브레이크_들었다_놨다.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '딕펑스_비바_청춘.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '소란_살빼지_마요.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '엔플라잉_옥탑방.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '멜로망스_선물.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4318'), (SELECT id FROM tracks WHERE audio_filename = '잔나비_뜨거운_여름밤은_가고_남은_건_볼품없지만.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = 'Taylor_Swift_Lover.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '10CM_폰서트.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '십센치_봄이_좋냐.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '소유X정기고_썸.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '악뮤_200.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '수지X백현_Dream.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '에릭남X웬디_봄인가_봐.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '로꼬X유주_우연히_봄.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '경서_나의_X에게.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '14-2311'), (SELECT id FROM tracks WHERE audio_filename = '주시크_너를_생각해.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = 'Cigarettes_After_Sex_Heavenly.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = 'Laufey_Fragile.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = 'LANY_Malibu_Nights.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '자이언트_핑크_너를_사랑하진_않아_feat_케이시.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '곽진언_자랑.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '가을방학_가을방학.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '루시드폴_보러_가자.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '김광석_거리에서.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '양희은_사랑_그_쓸쓸함에_대하여.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '11-4201'), (SELECT id FROM tracks WHERE audio_filename = '유재하_가리워진_길.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = 'Men_I_Trust_Show_Me_How.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '검정치마_기다린_만큼_더.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '혁오_Tomboy.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '카더가든_나무.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '최유리_밤_바다.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '김사월_머리맡.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '이소라_바람이_분다.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '토이_좋은_사람_feat_김형중.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '유희열_소박했던_행복했던.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '14-4102'), (SELECT id FROM tracks WHERE audio_filename = '정밀아_환란일기.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '선우정아_고양이_feat_IU.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '권진아_위로.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '박지윤_바래진_기억에.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '이적_빨래.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '김동률_기억의_습작.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '윤종신_오르막길.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '박새별_사랑이_우릴_다시_만나게_한다면.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '루네_누군가를_사랑한다는_것.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '이상은_비밀의_화원.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '16-3801'), (SELECT id FROM tracks WHERE audio_filename = '한희정_멜로디로_가득한_고백.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = 'Bruno_Major_Nothing.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = 'Keshi_2_soon.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '정세운_Beeeee.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '치즈_좋아해.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '샘김_그_여름밤.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '정은지_하늘바라기.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '멜로망스_동화.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '짙은_고래.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '에피톤_프로젝트_선인장.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '15-1214'), (SELECT id FROM tracks WHERE audio_filename = '가을방학_가끔_미치도록_네가_안고_싶어질_때가_있어.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = 'Travis_Scott_SICKO_MODE_2.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = 'Metallica_Enter_Sandman.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = 'Muse_Uprising.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = 'Radiohead_Creep.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = '서태지와_아이들_교실_이데아.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = '피아_소용돌이.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = '넬_Stay.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '19-4028'), (SELECT id FROM tracks WHERE audio_filename = '실리카겔_NO_PAIN.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '국카스텐_거울.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = 'Bring_Me_The_Horizon_Can_You_Feel_My_Heart.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = 'M_neskin_I_WANNA_BE_YOUR_SLAVE.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = 'Linkin_Park_Numb.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = 'Evanescence_Bring_Me_To_Life.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '시나위_크게_라디오를_켜고.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '김경호_나를_슬프게_하는_사람들.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '윤도현밴드_박하사탕.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '자우림_하하하쏭.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '19-1650'), (SELECT id FROM tracks WHERE audio_filename = '국카스텐_라젠카_세이브_어스.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Skrillex_Scary_Monsters.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Knife_Party_Bonfire.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Marshmello_Alone.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Alan_Walker_Faded.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Martin_Garrix_Tremor.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'DJ_Snake_Turn_Down_for_What.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Deadmau5_Strobe.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Daft_Punk_Harder_Better_Faster_Stronger.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Justice_D_A_N_C_E.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '19-0303'), (SELECT id FROM tracks WHERE audio_filename = 'Gesaffelstein_Pursuit.mp3'), 10),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Kendrick_Lamar_HUMBLE_2.mp3'), 1),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Post_Malone_Rockstar.mp3'), 2),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = '21_Savage_a_lot.mp3'), 3),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Central_Cee_Doja.mp3'), 4),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Pop_Smoke_Dior.mp3'), 5),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'XXXTENTACION_Look_At_Me.mp3'), 6),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'uicideboy_Kill_Yourself_Part_III.mp3'), 7),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Tyler_The_Creator_EARFQUAKE.mp3'), 8),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Playboi_Carti_Magnolia.mp3'), 9),
  ((SELECT id FROM playlists WHERE pantone_code = '18-1306'), (SELECT id FROM tracks WHERE audio_filename = 'Lil_Uzi_Vert_XO_Tour_Llif3.mp3'), 10)
ON DUPLICATE KEY UPDATE
  track_order = VALUES(track_order);

-- calendar_entries 테스트 데이터 (2026-03, testuser 기준)
INSERT INTO calendar_entries (user_uuid, entry_date, playlist_id, memo)
VALUES
  ((SELECT user_uuid FROM users WHERE id = 'testuser'), '2026-03-01', (SELECT id FROM playlists WHERE pantone_code = '18-1750'), '3월의 시작, 강렬한 무드'),
  ((SELECT user_uuid FROM users WHERE id = 'testuser'), '2026-03-02', (SELECT id FROM playlists WHERE pantone_code = '18-4245'), '차분하게 집중한 하루'),
  ((SELECT user_uuid FROM users WHERE id = 'testuser'), '2026-03-03', (SELECT id FROM playlists WHERE pantone_code = '18-1664'), '에너지 넘치게 작업'),
  ((SELECT user_uuid FROM users WHERE id = 'testuser'), '2026-03-04', (SELECT id FROM playlists WHERE pantone_code = '14-0760'), '조금은 뜨겁고 선명한 기분')
ON DUPLICATE KEY UPDATE
  playlist_id = VALUES(playlist_id),
  memo = VALUES(memo),
  updated_at = CURRENT_TIMESTAMP;
